"""Explicit source reviews. Choice indices are zero-based original positions."""
RADIO={
103178:(3,'The source concludes III only after rejecting I and II. Original option d reads ÍII only; retain that source spelling and record the typographic discrepancy separately.'),
104025:(0,'The conclusion gives both discontinuities x=-1 and x=2.'),
105291:(3,'The source explicitly names the full column vector [3;-1] as a2 before the dependence verification.'),
106929:(0,'The bold completed sentence identifies failure of closure under addition of polynomials in Y.'),
106930:(0,'The bold completed sentence identifies failure of closure under scalar multiplication of functions in L.'),
106933:(1,'The bold completed sentence identifies the absence of the zero element from I.'),
109247:(2,'The solution separately classifies A, B, and C as block lower triangular and names all three in its conclusion.'),
113918:(3,'The conclusion specifies the complete pair f(x)=e^x and b=6.'),
122932:(1,'The source rejects each numbered statement and explicitly says none give a partition of [-4,6].'),
123715:(2,'The source establishes convergence of each named sequence and explicitly selects a_n, b_n, and c_n.'),
181670:(4,'The source explicitly calls each of A, B, C infinite and selects all three.'),
22428:(3,'The source explicitly selects I and III only, matching the maximum and minimum statements in original order.'),
341642:(4,'The source explicitly concludes f, g, and h are piecewise continuous over the requested infinite interval.'),
47650:(0,'The conclusion gives all three points x=-2, x=0, and x=2 where the graph is not differentiable.'),
48080:(4,'The conclusion gives both discontinuities x=-2 and x=0.'),
48088:(4,'The conclusion gives both discontinuities x=-3 and x=0.'),
49234:(4,'The conclusion specifies the full pair f(x)=2e^x and b=ln(2).'),
66724:(1,'The source explicitly selects I, II, and III for invertibility on all three intervals.'),
75640:(4,'The source explicitly names the full column vector [20;-8] as a2, before later scalar coefficients.'),
75645:(1,'The source explicitly names the full column vector [-4;6;4] as a2; all three entries and signs are preserved.'),
78297:(4,'The opening source sentence names the full reflection matrix [1,0;0,-1]. Later images and transformed vectors are not the requested matrix.'),
78302:(0,'The opening source sentence names the full reflection matrix [0,-1;-1,0]. Preserve nested rows and columns.'),
94798:(3,'The bold completed sentence identifies failure of closure under multiplication by real scalars.'),
}
SELECT={
335401:(1,'field-1 binds L2 to L3. The source explicitly substitutes x-prime=Ax+g at this step.'),
335420:(2,'field-1 binds L2 to L3. The source explicitly substitutes x-prime=Ax+g, without the extra t0 distractor.'),
335422:(2,'field-1 binds L1 to L2. The source explicitly differentiates and uses the product rule.'),
335438:(4,'field-1 asks the justification of L1: the source explicitly calls 3x=O(3x) the reflexive property.'),
335445:(1,'field-1 asks the justification of L1: the source explicitly calls f=O(f) the reflexive property.'),
336106:(3,'field-1 asks what L1 names in Phi. The source says columns, specifically the fundamental solutions x1(t), x2(t).'),
336107:(0,'field-1 asks which line implies L2 by the fundamental-matrix definition. The source explicitly names L1.'),
336477:(2,'field-1 binds L2 to L3. The source evaluates both sides at t=0.'),
336711:(1,'field-1 binds L1 to L2. The source differentiates both sides with respect to t.'),
336716:(0,'field-1 binds L1 to L2. The source differentiates both sides; integrating belongs to the separate L6 to L7 field.'),
337121:(2,'field-1 binds L4 to L5. The source left-multiplies both sides by (e^(A t0))^-1, rather than using the inverse identity at the next step.'),
335183:(1,'field-1 is the top vector entry x(t); the final source vector is [cosh(7t)-1;sinh(7t)], with bottom entry fixed in the prompt.'),
337376:(0,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(3x), before solving u and y_p in fields 2 and 3.'),
337395:(4,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^x.'),
337466:(0,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(-4x).'),
337469:(0,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(-7x).'),
337488:(4,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(5x).'),
352890:(0,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(3x).'),
352895:(3,'field-1 asks the VOP assumed form. The source ansatz is y_p=u(x)e^(-3x).'),
}
SELECT.update({
335460:(0,'field-1 is the quantifier before solutions: the completed source sentence says Some, with arbitrarily close and eventually move away in the other fields.'),
335463:(2,'field-1 follows sufficiently: the completed asymptotic-stability sentence says close to.'),
335464:(0,'field-1 follows Some solutions starting: the completed source sentence says arbitrarily close to.'),
338004:(1,'field-1 classifies the first ODE sqrt(x)y-double-prime-2xy-prime+y=0; the corresponding source bullet explicitly says homogeneous.'),
338082:(0,'field-1 classifies y-double-prime+2y=x; the first source bullet explicitly says inhomogeneous.'),
338516:(0,'field-1 asks about the governing differential equation, whose source bullet explicitly says inhomogeneous; the boundary conditions have a different classification.'),
338646:(0,'field-1 asks about the governing equation, explicitly homogeneous in the solution; do not confuse with inhomogeneous boundary conditions.'),
338682:(0,'field-1 asks parity of x cos(x); the source explicitly concludes odd.'),
338686:(0,'field-1 asks the uniqueness criterion, explicitly det(A) nonzero in the source theorem, not a computed determinant.'),
338697:(1,'field-1 asks about the governing equation; the source explicitly calls it homogeneous.'),
338700:(1,'field-1 asks about the governing equation; the source explicitly calls it homogeneous, distinct from its boundary conditions.'),
338713:(0,'field-1 asks about the governing equation with sin(x) forcing; the source explicitly calls it inhomogeneous.'),
338982:(1,'field-1 asks the uniqueness criterion, explicitly det(A) nonzero in the source theorem.'),
339169:(0,'field-3 concerns the inhomogeneous BVP; the final source sentence says has at most one solution. Retain that exact qualifier rather than the old rejected unique-solution submission.'),
339176:(1,'field-1 asks the general uniqueness criterion det(A) nonzero, even though the later computed determinant for this particular BVP is zero.'),
339910:(1,'field-1 asks whether y_p=x is a particular solution; the first source substitution is checked and explicitly says is.'),
339913:(0,'field-1 asks whether y_p=x is a particular solution; the first source substitution is checked and explicitly says is.'),
340806:(0,'field-1 asks parity of x^3 cos(x); the source explicitly concludes odd.'),
341129:(0,'field-1 is table statement I about continuity on (-3,3). The source explicitly labels statement I true.'),
342410:(1,'field-1 is specifically x=-1; the corresponding source bullet explicitly calls it an irregular singular point. Preserve the source classification and do not reuse the incorrect submitted regular-singular choice.'),
342657:(1,'field-1 is table statement I about continuity on (-2,2). The source explicitly labels statement I false.'),
343289:(0,'field-3 asks the conclusion after W(0)=-1; the final source sentence explicitly says W(x) is nonzero for every real x.'),
343293:(0,'field-3 asks the conclusion after W(2)=0; the source explicitly says W(x)=0 for all x>0. Preserve the positive domain.'),
343295:(0,'field-3 asks the conclusion after W(0)=0; the source explicitly says W(x)=0 for all real x.'),
})
SELECT.update({
335748:(2,'field-1 is the numeric drag constant k, explicitly 16/3 in the source; field-2 separately supplies kg/s.'),
338837:(1,'field-1 asks eigenvalues. The source excludes zero and concludes lambda=-3/14 only, before giving the eigenfunction.'),
338853:(2,'field-1 asks eigenvalues. The source excludes zero and concludes lambda=-7/18 only.'),
338878:(0,'field-1 asks the absolute determinant. The source chain concludes (e^3-1)/e; do not use the signed determinant.'),
338905:(3,'field-1 asks both eigenvalues. The source explicitly gives lambda1=-1/10 and lambda2=1/20 in that order.'),
338907:(5,'field-2 asks the eigenfunction family. The final source expression is B_n sin(3 lambda_n x), including the factor 3.'),
339145:(1,'field-2 asks the IVP solution after the initial condition; the source final expression is 6-e^(-x^2/12), not the integrating factor.'),
339173:(3,'field-1 asks the absolute determinant; the source evaluates it as e-1/e.'),
340655:(0,'field-1 asks the whole Laplace transform of cosh(3t); the source chain concludes s/(s^2-9). Field-2 carries its domain.'),
340669:(1,'field-1 asks the inner product, evaluated as 0 in the source chain; orthogonality is the separate second field.'),
340883:(4,'field-1 asks the entire transform F(s); the final source gives e^(-2s)/s + e^(-5s)/s with both positive terms.'),
341136:(2,'field-1 asks the entire transform of cos(4t); the source chain concludes s/(s^2+16).'),
341140:(4,'field-1 asks the entire transform of sinh(8t); the source chain concludes 8/(s^2-64).'),
341448:(2,'field-1 asks the complete transform of the piecewise function. Preserve all three terms 2/s-2e^(-3s)/s+e^(3(1-s))/(s-1).'),
342960:(0,'field-2 asks the partial-fraction form Y(s); the source explicitly gives 3/[10(s+2)]-(3s+4)/[10(s^2+16)], before inverting.'),
346720:(4,'field-1 asks the approximation f(0.4), explicitly 2.2 in the source; the overestimate judgment is field-2.'),
365387:(2,'field-1 asks P(t), the coefficient of x. The final source explicitly gives 1/[t(t^2-1)], distinct from Q(t).'),
})
SELECT.update({
340418:(3,'field-1 is the first equality for a5, the source inner-product quotient <f,cos(5x)>/<cos(5x),cos(5x)>; the factor and integral occupy later fields.'),
340638:(4,'field-1 is the first equality for a6; the source gives <f,cos(6x)>/<cos(6x),cos(6x)>.'),
340645:(1,'field-1 is the first equality for a3 on [0,2pi); the source gives <f,cos(3x)>/<cos(3x),cos(3x)>.'),
341308:(4,'field-1 is the first equality for a0; preserve the factor 2 in the source quotient 2<f,1>/<1,1>.'),
343855:(0,'field-1 is the constant term a0/2, explicitly 2/3 in the source; a0 itself is 4/3.'),
343860:(1,'field-1 is the constant term a0/2, explicitly 1 in the source; a0 itself is 2.'),
343891:(0,'field-1 asks the harmonic index, explicitly n=3 in the source frequency comparison.'),
343899:(1,'field-1 asks the harmonic index, explicitly n=2 in the source frequency comparison.'),
343910:(3,'field-1 asks the harmonic index, explicitly n=3 in the source frequency comparison.'),
})
