"""Manual prompt-role reviews; values remain exact original authored options."""
REVIEW={
103567:'The solution rewrites this full equation in first-order linear standard form and explicitly rejects all other options.',
103991:'The final source equality explicitly gives the requested a+b=0, not either coefficient individually.',
105039:'The source explicitly names Z-negative subset N as the sole false statement, matching the prompt negation.',
105684:'The source identifies k=1 as the only option outside the guaranteed [2,66] range.',
105880:'The source explicitly calls this complete collection the only partition; preserve both nested subsets.',
105883:'The source explicitly calls {{0,2,4},{1,3,5}} the only partition, before rejecting the distractors.',
105973:'The source explicitly names the full pair of arithmetic-progression subsets as the only partition.',
105976:'The source explicitly selects {{0},{10,20,...,900}}. Preserve the singleton subset {0}.',
106293:'The source explicitly restricts theta to the closed interval [pi/2,pi] for the requested quarter-circle.',
106654:'The source explicitly names dy/dt=840-28y as the sole inhibited-decay equation and verifies y>30.',
106662:'The source explicitly names dy/dt=400-5y as the sole inhibited-growth equation and verifies y<80.',
106865:'The source evaluates dim(R15[t])=16 before its later general n+1 formula.',
106866:'The source evaluates dim(R20[t])=21 before its later general n+1 formula.',
106880:'The source evaluates dim(M3(R))=9, distinct from the preceding 2x2 example and following general formula.',
106888:'The source evaluates dim(M8(R))=64, distinct from its general formula.',
107125:'The source explicitly rounds the requested time to reach 40 degrees to 34 minutes; retain the unit.',
108921:'The concluding source sentence explicitly identifies the requested image of R^n as Col(A).',
109390:'The source gives the full Jordan matrix diag(2,1,-3), preserving three rows and columns.',
109395:'The source explicitly gives the Jordan matrix diag(4,-2,-2) for case II.',
109695:'The source concludes the requested sum a+b+c=3t^2-4 after identifying the three matrix entries.',
109696:'The source concludes the requested sum a+b+c=0, not any individual matrix entry.',
109720:'The source explicitly calls [1;0] a rank-2 generalized eigenvector for lambda=6 after checking both powers.',
109739:'The source explicitly calls [1;0] a rank-2 generalized eigenvector for lambda=5.',
109830:'The source explicitly calls [0;1;0;0] a rank-2 generalized eigenvector for lambda=3.',
109834:'The source explicitly calls [1;0;0;0] a rank-2 generalized eigenvector for lambda=3.',
}
HELD={}
REVIEW.update({
70743:'The source explicitly singles out 2/3 as the only option in the arccos domain.',
71396:'The source evaluates the gradient at (-1,0,1) and explicitly calls the full vector -2i+2k perpendicular to the requested surface.',
71399:'The source evaluates the gradient at (0,0,0) and explicitly calls 2i+2j+2k perpendicular to the requested surface.',
72303:'The source explicitly names the full saddle point (1,-4,5), including its z coordinate.',
72424:'The integration chain concludes -(7-2x)^8+C before differentiating to verify; retain the entire factor and integration constant.',
73894:'The source identifies -3 as the only zero in [-4,-1], binding to the common boundary a between the two signed-area integrals.',
74316:'The source explicitly classifies the full B matrix as lower triangular and rejects all other matrices.',
74650:'The source identifies k=2 as the value giving a redundant second equation and infinitely many solutions.',
74781:'The source explicitly concludes T(37v1+39v2)=[42;34;-28], preserving all three entries.',
74782:'The source explicitly concludes T(11v1+6v2)=[-35;-40;-45].',
74799:'The source explicitly concludes the requested LU-entry sum l21+u22=2.',
74983:'The source explicitly gives the singleton basis B={[-5;0;1]}; preserve the outer set and full column.',
75002:'The source explicitly calls B={[-9;-3;1]} a null-space basis; preserve singleton set braces.',
75024:'The source explicitly gives the complete three-vector basis {[0;1;0;0],[4;0;1;0],[-2;0;0;1]}.',
75025:'The source explicitly gives the complete two-vector basis {[-4;-1;1;0],[7;3;0;1]}.',
75177:'The source explicitly concludes l21+u22=-1/2.',
75519:'The source evaluates r(0) and explicitly names the point (1,1), not the parameter t=0.',
76110:'The source explicitly names (-2,3) as the correct interval from the original choices.',
76493:'The source explicitly rounds the requested product of angle values to 27,013.',
78500:'The source explicitly identifies [0;0;1] as a rank-2 generalized eigenvector for lambda=1.',
78501:'The source explicitly identifies [0;1;0] as a rank-2 generalized eigenvector for lambda=2.',
78575:'The source identifies [0;0;1;0] as satisfying the cube but not the square, binding to rank 3.',
79188:'The source explicitly gives the requested B+D=6 before its final curve equation.',
79494:'The source explicitly gives amplitude 1/3 m; retain the unit rather than the later full oscillation formula.',
80432:'The source explicitly calls the two odd-number subsets the only partition, preserving endpoints and nesting.',
80460:'The source integral chain gives the full vector antiderivative <t^3,e^t>+C with C a vector constant.',
80467:'The source eigenvector [2;1] is explicitly the first column of the final P=[2,1;1,1].',
80810:'The source explicitly calls Z subset N the only false statement.',
81372:'The source explicitly expresses the requested negated disjunction as not(P or Q).',
81402:'The source explicitly expresses the requested negated disjunction as not(P or Q).',
81772:'The source explicitly states v<0 exactly when 1<t<3, matching motion to the left and retaining open endpoints.',
83144:'The source explicitly rounds the subscribers after 12 weeks to 27,332.',
83480:'The source explicitly chooses the full eigenvector [1;1;1] for the requested eigenvalue 3.',
83481:'The source explicitly chooses the full eigenvector [1;2;1] for the requested eigenvalue 2.',
83505:'The source states t=1/2 is the only time satisfying both zero-velocity components.',
})
REVIEW.update({78978:'The final source classification explicitly gives a local minimum at x=2.',78981:'The final source classification explicitly gives a local maximum at x=1.',80917:'The source final sentence explicitly gives a=0, b=1/2, and requested sum 1/2.',80919:'The source final sentence explicitly gives a=0, b=1/4, and requested sum 1/4.',83477:'The final source bullet gives maximum value 0 at (0,0); the question asks value, not location.'})
REVIEW.update({
109943:'The source inserts 3sqrt(2) as the entire surface-area integrand; the slot asks for the integrand, not the evaluated area.',
109947:'The source inserts 2sqrt(18u^2+1) as the entire surface-area integrand, including its outer factor 2.',
109951:'The source inserts 2sqrt(u^4+v^4+4u^2v^2) as the full surface-area integrand.',
110214:'The source explicitly concludes P(X^2=9)=0.4 from the distribution table; an empty MathML block is irrelevant.',
110382:'The source explicitly gives the full Jordan matrix diag(4,3,0).',
110384:'The source explicitly gives the full Jordan matrix diag(-2,-3,-4).',
110413:'The source gives J1(3) plus J2(-2); preserve the single superdiagonal 1 at row 2 column 3.',
110438:'The source explicitly gives the full Jordan matrix diag(-2,-2,-3).',
110499:'The source explicitly gives J3(1), including both superdiagonal ones.',
110519:'The source explicitly gives J2(5) plus J1(5), with only the row-1 column-2 superdiagonal one.',
111309:'The source binds b=3 and d=0.4 to the requested table column, then explicitly gives b+d=3.4.',
111311:'The source binds a=6 and c=0.2 to the table, then explicitly gives a+c=6.2.',
111314:'The source explicitly gives the requested a+b+d=17.6 from the transformed distribution.',
111330:'The source explicitly gives a+c=15.35 from the transformed distribution.',
111349:'The source explicitly names the singleton basis {[-1;1;-3]}; retain the set braces.',
111398:'The source explicitly names the singleton basis {[4;2;1]}; retain the set braces.',
111478:'The source explicitly names the full two-vector null-space basis {[-2;1;0;0],[1;0;0;1]}.',
111520:'The source explicitly gives the requested table-parameter sum a+b+c=-3/4.',
111789:'The source concluding sentence identifies the image line y=-x/2.',
112815:'The source explicitly identifies x=0 as the root with multiplicity 2, distinguishing x=-6 with multiplicity 1.',
112968:'The source explicitly counts twenty distinct potential rational roots, including both signs.',
113502:'The integration chain gives -3/5(2-5x)^6+C before its derivative check.',
113509:'The integration chain gives -1/[2(x-2)^2]+C before its derivative check.',
113517:'The integration chain gives 1/[10(9-5x)^2]+C before its derivative check.',
115706:'The source concludes a=-2, b=1 and explicitly gives the requested sum -1.',
115910:'The source explicitly names the vertex (0,0), not the focal parameter -1/4.',
116051:'The source explicitly states the positive rate of decrease 12 m/min, distinct from signed derivative -12.',
116499:'The source explicitly states surface-area increase 280 square inches per minute; retain units.',
116755:'The source computes dV/dt=8 and states 8 cubic meters/hour. The volume derivative and units bind the requested answer despite the final prose calling it water level.',
117212:'The source explicitly identifies -pi/2 as outside the arccos domain, matching the prompt negation.',
117796:'The source explicitly concludes requested B+D=7/4 before its final tangent equation.',
117799:'The source explicitly concludes requested B+D=-9/4 before its final cotangent equation.',
118442:'The source explicitly identifies the graph as y=5sin(-x), retaining the original option form before the equivalent expression.',
})
REVIEW.update({109865:'The source specifically proves that the image of Col(A-transpose+B-transpose), the null-space orthogonal complement, is Col(A+B).',117969:'The final Euler table has x=4,y=1 and the concluding sentence explicitly says y(4) approximately 1; the incidental step-size match alone is not used.'})
REVIEW.update({
118443:'The source explicitly identifies the graph as y=6sin(-x) before showing its equivalent form.',
119039:'The second integration chain gives y=x^5+Cx+D with both arbitrary constants retained.',
120844:'The source explicitly states the particle is stationary at t=6 seconds.',
120911:'The third Euler step explicitly gives x_new=3 and y_new=2+2sqrt(2), binding to y(3).',
121736:'The source explicitly identifies t=2 as the only time satisfying both zero-velocity equations.',
122527:'The source gives f(r(t))=4-9t; the factor sqrt(10) is already outside the integral in the prompt.',
123292:'The full componentwise integration chain gives <e^(2t)/2+5t,sin(t+1)>+C, including the vector constant; retain the separate initial-line source typo.',
123294:'The source gives the full vector antiderivative <t^4+2t,t^2/8>+C.',
123320:'The source gives the full vector antiderivative <-cot(t),-cos(t)>+C, retaining both negative signs.',
125561:'The source explicitly binds e31 to row 3 column 1 and gives -3.',
125593:'The source explicitly binds r43 to row 4 column 3 and gives 1; the following full matrix is not the answer.',
126353:'The source explicitly calls the complete A=[1,-3;0,5] matrix upper triangular.',
127003:'The source explicitly calls [-4;3;-1] parallel to the line, distinct from its position vector.',
127033:'The source explicitly calls [7;5;-5] parallel to the line.',
127333:'The source normalizes T-prime(1) to N(1)=1/sqrt(5)<-2,1> before its subsequent orthogonality check.',
127583:'The source normalizes T-prime(0) to N(0)=1/2<sqrt(3),-1> before its subsequent dot-product check.',
127598:'The source gives the full N(0)=1/sqrt(2)<1,0,-1>, retaining the zero middle entry.',
127600:'The source gives N(0)=1/sqrt(2)(-j+k) before checking orthogonality.',
127736:'The source explicitly computes the full inverse Z^-1=1/2[8,-2;-3,1], including its outer scalar, before verifying the identity product.',
127737:'The source explicitly computes U^-1=[7,-3;5,-2] before verifying the identity product.',
128499:'The source gives the complete plane parametrization including both direction vectors and s,t over the whole real line.',
129480:'The source explicitly states CD is a 5x1 matrix.',
131116:'The source explicitly calls 3i-2j perpendicular to the level surface at (1,-1,-1).',
131386:'The source lists the two requested row operations R2+=10R1 then R2*=-1/2; the later inverse matrix is a different result.',
131999:'The source lists the two requested operations R1+=R2 then R2+=3R1, in that order.',
134085:'The source explicitly interprets (20,6) as six absences for the class of twenty students.',
135105:'The source final sentence gives initial velocity 70.6 m/s with units.',
136311:'The source rounds the requested speed magnitude to 5.39 m/s.',
136312:'The source rounds the requested speed magnitude to 4.12 km/h, preserving the original units.',
136355:'The source evaluates velocity at three seconds and rounds its magnitude to 9.22 m/s.',
139274:'The source explicitly names R3:=R3+(-2)R2 as the required row operation, before a separate inverse matrix.',
139454:'The source identifies [1;0;0] as satisfying (A+4I)^3v=0 but not the square, binding to rank 3.',
140117:'The source explicitly computes the orthogonal component z=[-6;2;-2;-1], distinct from the projection y.',
})
REVIEW.update({122663:'The final source intersection D1 intersect D2 explicitly gives {(x,y) in R^2 | x>y^2} as the full vector-field domain.',126166:'The source explicitly states f-prime and f have the same Taylor radius, then concludes R=infinity.'})
REVIEW.update({
140579:'The source identifies x=1 as the shared boundary between the two signed-area regions, binding to a in both integral limits.',
141113:'The source initial-condition chain explicitly gives A=-4; the later solution y=-4/x^2 is not the requested constant.',
141115:'The source explicitly solves A=e-1 before substituting into the full IVP solution.',
141116:'The source explicitly solves A=2 before substituting into y=1/(2+x).',
141999:'The source explicitly computes the requested B+2D=4, not B+D.',
142000:'The source explicitly computes requested B+D=4 before its final graph equation.',
143669:'The source explicitly computes requested B-2D=17/2.',
149766:'The source explicitly binds a=-3,b=5,c=0.1 and gives a+b+c=2.1.',
160559:'The missing second coordinate is y(u,v); the source final transformation explicitly gives sqrt(uv).',
161086:'The missing first coordinate is x(u,v); the source explicitly gives sqrt(v/u).',
161251:'The source calculates the flux integrand F(r) dot (r_u cross r_v) as -5u^3, matching the sole box.',
161357:'The source calculates the full flux integrand as 5u-6v for the given parametrization.',
161359:'The source calculates the full flux integrand as u^2-uv+v^2.',
161360:'The source calculates the flux integrand as 2uv, rather than its later integrated value.',
161383:'The source calculates the complete flux integrand uv^2-uv+u^2v.',
161550:'The source gives the full boundary set with defining equation 2y=x^2; only that equation fills the missing predicate.',
161596:'The source gives the full boundary set with defining equation y^2=-x.',
161598:'The source gives the full boundary set with defining equation x^2+4y^2=36.',
162581:'The source divergence is x^2+y+2, which it places in the triple integral; the box asks the integrand.',
162583:'The source divergence is 6x-z, which it places in the triple integral.',
162644:'The source explicitly excludes t=pi/6+pi*n/3 for integer n; the slot follows t not-equal, so only this full family fills it.',
163839:'The source explicitly states global maximum value 10, distinguishing the two points attaining it.',
164249:'The source explicitly states radius 4 after writing the sphere RHS as 4 squared.',
164412:'The source explicitly names the xy-projection vertex (-2,-3); the fixed z=4 is not part of this planar answer.',
165039:'The source evaluates r(-1) and explicitly names the requested point (-5/2,-6), not the time -1.',
175312:'The source explicitly translates the negation of x=3 as x not-equal 3.',
175315:'The source explicitly translates the negation of membership in R as x not-in R.',
176834:'The source explicitly names the full cone center (3,-2,1).',
176865:'The source explicitly translates the sentence as not P or Q, with negation only on P.',
178256:'The source explicitly identifies x=5 as the multiplicity-2 root and distinguishes the simple root -5.',
178288:'The source evaluates the requested three-term binomial approximation as 0.9321 to four decimals.',
180821:'The source explicitly selects {0,1,{0},{1}}; preserve scalar elements and singleton set elements separately.',
181611:'The source explicitly selects {a,b,c,d}, preserving scalars rather than singleton subsets.',
181619:'The source explicitly selects {x,u,v,w}, preserving the authored element order.',
181636:'The source explicitly selects {2,{2},4,{2,4}}; all outer and inner set braces are significant.',
})
